### ISSUE TITLE
Unknown predicate in Wikidata taxonomy

### ISSUE THREAD

**Issue by mommi84** [deepschema/deepschema.github.io#1]
Hi! I've found a URI (`http://www.wikidata.org/entity/P373c`) used as a datatype property in the Wikidata taxonomy, however I cannot find its definition anywhere. What is it supposed to be? Thanks.

**Comment by psmeros** [comment]
Dear Tommaso,

This URI can only be found in the RDF dump of Wikidata taxonomy and it exists due to the mapping from JSON to RDF (https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format).

As Wikidata developers recommend the JSON dump of the full dataset (https://www.wikidata.org/wiki/Wikidata:Database_download), I would recommend the same for the deepschema.org products.

Kind Regards,
Panayiotis

**Comment by mommi84** [comment]
Thanks. So, this means many properties were purposely created without the possibility to be dereferenced. Good to know!
